-- Ingresos Proyectados: excluir BAJAS (antes se contaban las cuotas de estudiantes dados de baja).
-- La MORA sí se considera ingreso proyectado (decisión de Anneris): el recargo por pago fuera de
-- término es plata que se espera cobrar, así que se incluye.
-- Se agrega el campo 'ingresos_proyectados' a las RPC stats_cohorte y stats_programa.
-- Fórmula por cuota (solo ARS, con monto definido, no "No aplica", estudiante NO de baja):
--   falta = greatest(0, monto_final - abonado)          -- monto_final incluye el recargo de mora
--   abonado = monto_abonado (si >0) | (monto_final - saldo_pendiente)
-- Las definiciones completas de ambas funciones se aplicaron vía CREATE OR REPLACE
-- (ver stats_cohorte y stats_programa en la base). Este archivo documenta el cambio del campo.
